using System.Text;
using System.Text.RegularExpressions;
using FluentAssertions;

namespace DjVisualizer.Api.IntegrationTests;

/// <summary>
/// The demo assets are the only files this repository ships that a public deployment serves back
/// to strangers, so they are the one place where personal data could plausibly escape. They are
/// generated by scripts/generate-demo-assets.sh from synthesized tones and a drawn gradient -
/// there is no export step from a real device anywhere in that pipeline. This test enforces that
/// property rather than trusting it, because the failure mode of someone quietly swapping in a
/// real track is silent and permanent.
/// </summary>
public class DemoAssetSafetyTests
{
    private static readonly string[] AssetFileNames = ["sample-mix.mp3", "sample-artwork.png"];

    /// <summary>Patterns that should never appear in a fixture that was generated rather than
    /// exported from a real device.</summary>
    private static readonly (string Name, Regex Pattern)[] ForbiddenPatterns =
    [
        ("email address", new Regex(@"[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}", RegexOptions.Compiled)),
        ("URL", new Regex(@"https?://[^\s""']+", RegexOptions.Compiled | RegexOptions.IgnoreCase)),
        ("phone number", new Regex(@"(?<![\d.])(\+\d{1,3}[\s.\-]?)?\(?\d{3}\)?[\s.\-]\d{3}[\s.\-]\d{4}(?![\d.])", RegexOptions.Compiled)),
        ("credential-like token", new Regex(@"(?i)(api[_\-]?key|secret|password|passwd|bearer|token)\s*[:=]", RegexOptions.Compiled)),
        ("private key block", new Regex(@"BEGIN [A-Z ]*PRIVATE KEY", RegexOptions.Compiled)),
        ("Windows user path", new Regex(@"[A-Za-z]:\\Users\\", RegexOptions.Compiled)),
        ("Unix home path", new Regex(@"/(home|Users)/[A-Za-z0-9._\-]+", RegexOptions.Compiled)),
    ];

    private static string RepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "docker-compose.yml")))
        {
            directory = directory.Parent;
        }

        directory.Should().NotBeNull("the repository root should be discoverable from the test output directory");
        return directory!.FullName;
    }

    public static TheoryData<string> AssetNames() => [.. AssetFileNames];

    [Theory]
    [MemberData(nameof(AssetNames))]
    public void The_Bundled_Demo_Asset_Exists(string fileName)
    {
        File.Exists(Path.Combine(RepositoryRoot(), "assets", "demo", fileName)).Should().BeTrue(
            "the demo endpoint serves this file; regenerate it with scripts/generate-demo-assets.sh");
    }

    [Theory]
    [MemberData(nameof(AssetNames))]
    public void The_Bundled_Demo_Asset_Contains_Nothing_That_Looks_Personal(string fileName)
    {
        var bytes = File.ReadAllBytes(Path.Combine(RepositoryRoot(), "assets", "demo", fileName));

        // Latin1 rather than UTF-8: it maps every byte to a character, so no run of bytes can be
        // dropped as invalid and thereby hide a match.
        var text = Encoding.Latin1.GetString(bytes);

        foreach (var (name, pattern) in ForbiddenPatterns)
        {
            var match = pattern.Match(text);
            match.Success.Should().BeFalse(
                "{0} must contain no {1}, but found '{2}' at offset {3}", fileName, name, match.Value, match.Index);
        }
    }

    /// <summary>
    /// Container metadata is the easiest thing to forget about: an exported file routinely names
    /// the software, the device, the album, and sometimes the person. Asserted structurally by
    /// reading the actual chunk and frame headers rather than by scanning for printable runs -
    /// MP3 frame data is compressed, so a text heuristic false-positives on ordinary audio noise.
    /// </summary>
    [Fact]
    public void The_Sample_Artwork_Carries_No_Png_Text_Chunks()
    {
        var text = Encoding.Latin1.GetString(
            File.ReadAllBytes(Path.Combine(RepositoryRoot(), "assets", "demo", "sample-artwork.png")));

        foreach (var chunkType in new[] { "tEXt", "iTXt", "zTXt" })
        {
            text.Should().NotContain(chunkType, "PNG {0} chunks carry arbitrary author-supplied metadata", chunkType);
        }
    }

    [Fact]
    public void The_Sample_Mix_Carries_Only_Ffmpegs_Own_Encoder_Frame()
    {
        var bytes = File.ReadAllBytes(Path.Combine(RepositoryRoot(), "assets", "demo", "sample-mix.mp3"));

        Encoding.Latin1.GetString(bytes, 0, 3).Should().Be("ID3", "ffmpeg writes an ID3v2 header");

        // ID3v2 size is a synchsafe integer: four bytes, each contributing only its low 7 bits.
        var tagSize = (bytes[6] << 21) | (bytes[7] << 14) | (bytes[8] << 7) | bytes[9];
        var tagRegion = Encoding.Latin1.GetString(bytes, 10, tagSize);

        // TSSE is "encoding settings" - the Lavf stamp ffprobe reports. Anything else (TIT2 title,
        // TPE1 artist, COMM comment, APIC embedded artwork) would be descriptive metadata this
        // fixture must not carry, since it is generated rather than exported from anywhere.
        var frameIds = Regex.Matches(tagRegion, @"(?<![A-Z0-9])[A-Z][A-Z0-9]{3}")
            .Select(match => match.Value)
            .Distinct()
            .ToList();

        frameIds.Should().OnlyContain(id => id == "TSSE",
            "the generated fixture should carry no descriptive tags, but found {0}", string.Join(", ", frameIds));

        // ID3v1 lives in the last 128 bytes and would carry title/artist/album/comment fields.
        Encoding.Latin1.GetString(bytes, bytes.Length - 128, 3).Should().NotBe("TAG");
    }
}
